name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "Iniciando login . . ."
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "Finalizando login . . ."
    
    - name: Docker BUILD image
      run: |
        docker build -t ricardolara99/docker-graphql:0.0.1 .
    
    - name: Docker PUSH image
      run: |
        docker push ricardolara99/docker-graphql:0.0.1
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
